version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - task-storage:/data

  postgres_db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_db-data: null
  task-storage: null